# Generated by Django 3.1.2 on 2020-11-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20201115_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(blank=True, choices=[('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.')], default='', max_length=60),
        ),
    ]
